- name: setup custom repo
  apt: pkg=python-pycurl state=present
#- apt_repository: repo='ppa:jmartin-1/tools'

- name: enable carbon
  copy: dest=/etc/default/graphite-carbon content='CARBON_CACHE_ENABLED=true'

- name: install graphite and deps
  apt: name={{ item }} state=present
  with_items: packages

#- name: setup apache
#  copy: src=apache2-graphite.conf dest=/etc/apache2/sites-available/default
#  notify: restart apache

- name: configure wsgi
  file: path=/etc/apache2/wsgi state=directory

- name: configure apache default
  command: "a2dissite 000-default"

- name: setup apache graphite configuration
  command: "cp /usr/share/graphite-web/apache2-graphite.conf /etc/apache2/sites-available"

- name: enable graphite apache"
  command: "a2ensite apache2-graphite"
  notify:
    - restart apache